//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateDDNS.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateDDNS.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 正在检测主机名{1}.{2}是否存在..
        /// </summary>
        public static string DetectName {
            get {
                return ResourceManager.GetString("DetectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.{2}更新后的IP地址为{3}.
        /// </summary>
        public static string EndUpdate {
            get {
                return ResourceManager.GetString("EndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 正在访问{1}的对象..
        /// </summary>
        public static string LoadObject {
            get {
                return ResourceManager.GetString("LoadObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 组装AliyunService和GodaddyService对象.
        /// </summary>
        public static string LoadObjects {
            get {
                return ResourceManager.GetString("LoadObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 读取配置文件..
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 本地IP地址{1}与解析记录{2}不同, 需要进行更新操作!.
        /// </summary>
        public static string NeedUpdate {
            get {
                return ResourceManager.GetString("NeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 没有找到{1}.{2}的解析记录..
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 本地IP地址与解析IP相同, 不需要更新解析记录。.
        /// </summary>
        public static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: UpdateDDNS程序退出.
        /// </summary>
        public static string ProgramEnd {
            get {
                return ResourceManager.GetString("ProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: UpdateDDNS程序启动.
        /// </summary>
        public static string ProgramStart {
            get {
                return ResourceManager.GetString("ProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 开始更新解析记录{1}.{2}, 新的IP为{3}.
        /// </summary>
        public static string StartUpdate {
            get {
                return ResourceManager.GetString("StartUpdate", resourceCulture);
            }
        }
    }
}
